# Generated by Django 5.2.1 on 2025-05-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Support name')),
                ('email', models.EmailField(max_length=254, verbose_name='Support email')),
                ('text', models.TextField(verbose_name='Support text')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car name')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Car image')),
                ('price', models.PositiveIntegerField(verbose_name='Car price')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_car', to='main.brand')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
